version: "3.7"
networks:
  network-tds-reports:
    name: network-tds-reports
    driver: bridge

services:
  minio:
    container_name: minio
    image: minio/minio
    user: root
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/Desktop/tds-reports/minio/data:/data
    command: server /data --console-address ":9090"
    networks:
      - network-tds-reports

  pdf-turtle:
    container_name: pdf-turtle
    image: lucasgaitzsch/pdf-turtle
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: ${PDF_TURTLE_DEV_PORT}
      SERVE_PLAYGROUND: ${PDF_TURTLE_DEV_SERVE_PLAYGROUND}
    networks:
      - network-tds-reports

  mockoon:
    container_name: mockoon
    image: mockoon/cli:latest
    ports:
      - "8080:8080"
    volumes:
      - ./UCB_ACAD_SOFT.json:/data
    command: ["--data", "data"]
    networks:
      - network-tds-reports

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    restart: always
    user: root
    ports:
      - "1433:1433"
    volumes:
      - ~/Desktop/tds-reports/sql-server/data:/var/opt/mssql/
    environment:
      SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}
      ACCEPT_EULA: Y
    networks:
      - network-tds-reports

  backend:
    container_name: tds-reports-backend
    image: thealanmc/tds-reports-backend:0.1.3
    restart: always
    user: root
    ports:
      - "5260:80"
    volumes:
      - ~/Desktop/tds-reports/backend/Utils:/Utils
    networks:
      - network-tds-reports

  frontend:
    container_name: tds-reports-frontend
    image: thealanmc/tds-reports-frontend:0.1.0
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/Desktop/tds-reports/angular/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - network-tds-reports

